import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navmenu from "@/components/home/Navmenu";
import Footer from "@/components/home/Footer";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Toaster position="top-center" richColors theme="light"/>
        {/* Reserve bottom space on small screens so fixed bottom nav doesn't cover the footer */}
        <main className="min-h-screen pb-16 md:pb-0">{children}
          <Footer />
        </main>

        <Navmenu />
      </body>
    </html>
  );
}
